analytics: {}
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0.498873
  rhythmicContrast: 0.525237
  saturation: 0.492117
cta: {}
layout_spectrum: 0.230855
name: "OMG! I'm Alive!"
opengraph: {}
purpose: []
typography_spectrum: 0.48536
