name: "OMG! I'm Alive!"
favicon: null
layout_spectrum: 0.25839
typography_spectrum: 0.13043
title: "OMG! I'M ALIVE!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c9ddea'
    - '#423244'
    - '#000001'
    - '#787771'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
