name: "OMG! I'm Alive!"
favicon: null
layout_spectrum: 0.8567166954744607
typography_spectrum: 0.7788386377505958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6871194334235042
  lightness: 0.9340621784795076
  saturation: 0.11489461385644972
  rhythmicContrast: 0.5252375060226768
purpose: []
